version: 0.1
bridge: Guardian-MySQL-0.1-SNAPSHOT
debug: false
ninja: false
werollback: true
consumerDelay: 6
tools:
    tool:
        permissionDefault: 'TRUE'
        item: 270
        leftClickBehavior: NONE
        params: area 0 all sum none limit 15 desc silent
        rightClickBehavior: TOOL
        aliases:
        - t
        defaultEnabled: true
        mode: LOOKUP
        give: true
    toolblock:
        permissionDefault: 'TRUE'
        item: 7
        leftClickBehavior: TOOL
        params: area 0 all sum none limit 15 desc silent
        rightClickBehavior: BLOCK
        aliases:
        - tb
        defaultEnabled: true
        mode: LOOKUP
        give: true
